# Generated by Django 5.2.7 on 2025-11-14 00:55

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tier', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/icons/')),
                ('rank', models.PositiveIntegerField(default=1, unique=True)),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('max_level', models.PositiveIntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Future_Of_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(error_messages={'unique': 'Email Address already exists.'}, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Phone number already exists.'}, max_length=128, region=None, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('course_type', models.CharField(choices=[('', 'Select course type...'), ('web3', 'Web3 Fundamentals'), ('dao', 'DAO Governance'), ('metaverse', 'Metaverse Collaboration'), ('blockchain', 'Blockchain Development')], default='', max_length=20)),
                ('plan_preference', models.CharField(choices=[('', 'Select plan...'), ('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('exclusive', 'Exclusive')], default='', max_length=20)),
                ('expertise', models.CharField(choices=[('', 'Select your level...'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('gateway', models.CharField(blank=True, choices=[('helio', 'Helio'), ('paystack', 'Paystack'), ('opay', 'OPay')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.CharField(choices=[('Creator', 'Creator'), ('Builder', 'Builder'), ('Educator', 'Educator'), ('Community', 'Community')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('locked', models.BooleanField(default=False)),
                ('do_type', models.CharField(blank=True, max_length=50)),
                ('earn_type', models.CharField(blank=True, max_length=50)),
                ('xp_amount', models.PositiveIntegerField(default=0)),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='future_of_work.badge')),
                ('prerequisites', models.ManyToManyField(blank=True, to='future_of_work.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('pod', models.CharField(blank=True, choices=[('Creator', 'Creator'), ('Builder', 'Builder'), ('Educator', 'Educator'), ('Community', 'Community')], max_length=64)),
                ('goal', models.CharField(blank=True, choices=[('Get Skilled', 'Get Skilled'), ('Build Projects', 'Build Projects'), ('Find Work', 'Find Work'), ('Collaborate', 'Collaborate')], max_length=128)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('streak_current', models.PositiveIntegerField(default=0)),
                ('streak_best', models.PositiveIntegerField(default=0)),
                ('last_active_day', models.DateField(auto_now_add=True)),
                ('xp_learn', models.PositiveIntegerField(default=0)),
                ('xp_do', models.PositiveIntegerField(default=0)),
                ('xp_earn', models.PositiveIntegerField(default=0)),
                ('referral_code', models.CharField(blank=True, max_length=32, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=32, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_connected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('badges', models.ManyToManyField(blank=True, related_name='users', to='future_of_work.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_score', models.PositiveIntegerField(blank=True, null=True)),
                ('file_submission', models.FileField(blank=True, null=True, upload_to='lesson_uploads/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='future_of_work.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
