# Generated by Django 5.2.7 on 2025-11-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_of_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('Get Skilled', 'Get Skilled'), ('Build Projects', 'Build Projects'), ('Find Work', 'Find Work'), ('Collaborate', 'Collaborate')], max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pod',
            field=models.CharField(blank=True, choices=[('Creator', 'Creator'), ('Builder', 'Builder'), ('Educator', 'Educator'), ('Community', 'Community')], max_length=64),
        ),
    ]
