# Generated by Django 5.2.7 on 2025-11-14 17:33

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_of_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
