# Generated by Django 5.2.7 on 2025-11-21 18:52

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_of_work', '0002_alter_lesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Email Address already exists.'}, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Phone number already exists.'}, max_length=128, region=None, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user_type', models.CharField(choices=[('', 'Select your status...'), ('tutee', 'Student'), ('tutor', 'Educator')], default='', max_length=20)),
            ],
        ),
    ]
