# Generated by Django 5.2.7 on 2025-11-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_of_work', '0002_alter_userprofile_goal_alter_userprofile_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
